services:
  nextjs:
    build:
      context: ..  # This sets the build context to the root of your project, which contains both 'my-world-fe' and 'my-world-docker'
      dockerfile: ./my-world-docker/containers/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../my-world-fe:/app  # Bind 'my-world-fe' to /app in the container
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
